name: Package Code Editor with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
  
    - name: Package Main Executable
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: /
        spec: main.spec

    - name: Package Interpreter Executable
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: interpreter
        spec: interpreter/interpreter.spec
  
    - uses: actions/upload-artifact@v2
      with:
        name: main.exe
        path: /dist/


  
